// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bdgajfmiirlfumfcunkw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJkZ2FqZm1paXJsZnVtZmN1bmt3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0NTAwODUsImV4cCI6MjA2NzAyNjA4NX0.lnmH8Pwa3E89STwGd6_YaKtrdyoSa2gCXxga-JG0y0k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});